version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=/api
        - VITE_MAX_FILE_SIZE=10485760
        - VITE_BATCH_SIZE=100
    restart: unless-stopped
    networks:
      - coolify

networks:
  coolify:
    external: true
