version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: siret-extractor-backend:1.0.0
    environment:
      # API Configuration
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - API_WORKERS=1
      - DEBUG=False
      - ALLOWED_ORIGINS=https://siretextractor.lasupermachine.fr

      # Scraper Configuration
      - MAX_CONCURRENT_WORKERS=10
      - REQUEST_TIMEOUT=30000
      - NAVIGATION_TIMEOUT=60000
      - PAGE_LOAD_TIMEOUT=30000

      # Browser Configuration
      - HEADLESS=True
      - BROWSER_TYPE=chromium

      # Proxy Configuration
      - PROXY_ROTATION_ENABLED=True
      - PROXY_LIST=

      # Rate Limiting
      - RATE_LIMIT_REQUESTS=100
      - RATE_LIMIT_WINDOW=60

      # Retry Configuration
      - MAX_RETRIES=3
      - RETRY_DELAY=2

    restart: unless-stopped

    healthcheck:
      test:
        - CMD-SHELL
        - 'curl -f http://127.0.0.1:8000/health'
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '1.0'
          memory: 1G

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    networks:
      - coolify

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=
        - VITE_MAX_FILE_SIZE=10485760
        - VITE_BATCH_SIZE=100
    image: siret-extractor-frontend:1.0.0

    environment:
      # Coolify routing - PATTERN DASHY
      - SERVICE_URL_FRONTEND_80

    depends_on:
      backend:
        condition: service_healthy

    healthcheck:
      test:
        - CMD-SHELL
        - 'wget -qO- http://127.0.0.1:80/'
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

    restart: unless-stopped

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    networks:
      - coolify

networks:
  coolify:
    external: true
