version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: siret-extractor-backend:1.0.0
    container_name: siret-extractor-backend
    environment:
      # API Configuration
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - API_WORKERS=4
      - DEBUG=False
      - ALLOWED_ORIGINS=https://siretextractor.lasupermachine.fr

      # Scraper Configuration
      - MAX_CONCURRENT_WORKERS=10
      - REQUEST_TIMEOUT=30000
      - NAVIGATION_TIMEOUT=60000
      - PAGE_LOAD_TIMEOUT=30000

      # Browser Configuration
      - HEADLESS=True
      - BROWSER_TYPE=chromium

      # Proxy Configuration
      - PROXY_ROTATION_ENABLED=True
      - PROXY_LIST=

      # Rate Limiting
      - RATE_LIMIT_REQUESTS=100
      - RATE_LIMIT_WINDOW=60

      # Retry Configuration
      - MAX_RETRIES=3
      - RETRY_DELAY=2

    # Restart policy
    restart: unless-stopped

    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '1.0'
          memory: 1G

    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "siret-extractor-backend"

    # Network
    networks:
      - siret-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=/api
        - VITE_MAX_FILE_SIZE=10485760
        - VITE_BATCH_SIZE=100
    image: siret-extractor-frontend:1.0.0
    container_name: siret-extractor-frontend
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - VITE_API_BASE_URL=/api
      - VITE_MAX_FILE_SIZE=10485760
      - VITE_BATCH_SIZE=100

    # LABELS TRAEFIK - Configuration pour Coolify/Traefik
    labels:
      # Enable Traefik for this container
      - "traefik.enable=true"

      # HTTP Router configuration
      - "traefik.http.routers.siret-frontend.rule=Host(`siretextractor.lasupermachine.fr`)"
      - "traefik.http.routers.siret-frontend.entrypoints=websecure"
      - "traefik.http.routers.siret-frontend.tls=true"
      - "traefik.http.routers.siret-frontend.tls.certresolver=letsencrypt"

      # Service configuration - point to port 80 inside container
      - "traefik.http.services.siret-frontend.loadbalancer.server.port=80"

      # HTTP to HTTPS redirect
      - "traefik.http.routers.siret-frontend-http.rule=Host(`siretextractor.lasupermachine.fr`)"
      - "traefik.http.routers.siret-frontend-http.entrypoints=web"
      - "traefik.http.routers.siret-frontend-http.middlewares=https-redirect"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https-redirect.redirectscheme.permanent=true"

    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "siret-extractor-frontend"
    networks:
      - siret-network

networks:
  siret-network:
    driver: bridge
